config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  root to: "home#index"

  get 'pets/all' => 'pets#index'
  get 'pets/user' => 'pets#return_user_pets'
  get 'pets/:id/info' => 'pets#show'
  
  post 'pets/form' => 'pets#return_form'

  post 'pets/create' => 'pets#create'
  post 'pets/update' => 'pets#update'
  post 'pets/destroy' => 'pets#destroy'

end

app/models/pet.rb
class Pet < ActiveRecord::Base

  after_find :instance_variables

  cattr_reader :animal_species
  @@animal_species = %w(cat dog bird fish reptile rodent exotic)

  has_attached_file :image, styles: { thumb: "100x100>", zoom:"400x400>" }, default_url: "/images/:style/missing.png"
  
  validates_attachment_content_type :image, content_type: /\Aimage.*\Z/
  validates_attachment_presence :image, attachment_presence: true
  validates_attachment_size :image, :less_than => 15.megabyte

  attr_reader :user_name, :images_urls, :age

  def instance_variables
    @user_name = user.name
    @images_urls = {
      original: image.url(:original),
      zoom: image.url(:zoom),
      thumb: image.url(:thumb) 
    }
    @age = return_age_string
  end

  validates :name, :animal, :user_id, presence: true
  validates :name, length: { maximum: 15 }
  validates :animal, inclusion: { in: @@animal_species }
  validates_date :birth, :on_or_before => :today

  belongs_to :user

  scope :desc_sorted_by_id, -> { all.order({id: :desc}) }

  def return_age_string
    if self.birth
      number_years = Date.today.year - self.birth.year
      number_months = Date.today.month - self.birth.month

      #this condition fix when the year has changed but days < 364
      range_date = self.birth..Date.today
      number_days = range_date.reduce(0) {|s,d| s + 1}
      condition_below_a_year_fix = number_days < 364

      #this condition show when age < month
      condition_below_a_month_fix = Date.today.day < self.birth.day && number_months <= 1 

      if number_months == 0 && number_years == 0
        age_string = "#{number_days} days"
      elsif number_years == 0 || condition_below_a_year_fix
        if condition_below_a_month_fix
          age_string = "#{number_days} days"
        else
          number_months = 12 - number_months.abs if number_months < 0
          age_string = "#{number_months} months"
        end
      else
        age_string = "#{number_years} years"
      end
    else
      age_string = 'unknowed'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :recoverable, :trackable, :confirmable, :lockable and :omniauthable
  devise :database_authenticatable, :registerable, :timeoutable,
         :rememberable, :validatable

  validates :name, uniqueness: true
  validates :name, presence: true
  validates :name, length: { maximum: 25 }
  validates :name, format: { with: /\A[a-zA-Z]+.+/, on: :create }

  has_many :pets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #helper :all
  
  before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    render 'index'
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  
  before_action :authenticate_user!

  LIMIT_LIST = 30
  DATAS_INCLUDE = {
    :only => [:id, :name, :animal, :birth],
    :methods => [:user_name, :images_urls, :age]
  }

  #get 'pets/all'
  def index
    pets_list = Pet.desc_sorted_by_id.limit(LIMIT_LIST)
    if pets_list.size > 0
      render status: :ok, :json => pets_list.to_json(DATAS_INCLUDE)
    else
      render status: :not_found, :json => { error: "pets list not found"}
    end
  end

  #get 'pets/user'
  def return_user_pets
    pets_list = current_user.pets.desc_sorted_by_id
    if pets_list.size > 0
      render status: :ok, :json => pets_list.to_json(DATAS_INCLUDE)
    else
      render status: :not_found, :json => { error: "pets list not found"}
    end
  end

  #get 'pets/:id/info'
  def show
    pet = Pet.find_by_id(params[:id])
    if pet
      render status: :ok, json: pet.to_json(DATAS_INCLUDE)
    else
      render status: :not_found, :json => { error: "pet not_found"}
    end
  end

  #post 'pets/form'
  def return_form
    if params[:pet]
      @pet = Pet.find_by_id(pet_params[:id])
    elsif
      @pet = Pet.new
    end
    render 'form', layout: 'clean'
  end

  #post 'pets/create'
  def create
    pet = current_user.pets.create(pet_params)
    if pet.save
      flash[:notice] = 'Pet created'
      #render status: :created, json: pet.to_json #this is single page version
      redirect_to(root_path)
    else
      flash[:alert] = 'Error: Unprocessable entity'
      #render status: :unprocessable_entity, :json => { error: "unprocessable"} #this is single page version
      redirect_to(root_path)
    end
  end

  #post 'pets/update'
  def update
    if pet_params[:id]
      pet = current_user.pets.find_by_id(pet_params[:id])
      if pet.update_attributes(pet_params)
        flash[:notice] = 'Pet updated'
        #render status: :accepted, :json => pet.to_json #this is single page version
        redirect_to(root_path)
      else
        flash[:alert] = 'Error: Unprocessable entity'
        #render status: :unprocessable_entity, :json => { error: "unprocessable"} #this is single page version
        redirect_to(root_path)
      end
    else
      flash[:alert] = 'Error: Pet not found'
      #render status: :not_found, :json => { error: "not_found"} #this is single page version
      redirect_to(root_path)
    end
  end

  #post 'pets/destroy'
  def destroy
    if pet_params[:id]
      pet = current_user.pets.find_by_id(pet_params[:id])
      if pet.destroy
        flash[:notice] = 'Pet deleted'
        #render status: :ok, :json => nil.to_json #this is single page version
        redirect_to(root_path)
      else
        flash[:alert] = 'Error: Unprocessable entity'
        #render status: :unprocessable_entity, :json => { error: "unprocessable"} #this is single page version
        redirect_to(root_path)
      end
    else
      flash[:alert] = 'Error: Pet not found'
      #render status: :not_found, :json => { error: "not_found"} #this is single page version
      redirect_to(root_path)
    end
  end

private

  def pet_params
    params.require(:pet).permit(:id, :name, :animal, :birth, :image) 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pets_helper.rb
module PetsHelper

end

app/views/home/index.html.erb
<%= render "shared/devise_alerts" %>
<blockquote class="blockquote-reverse">
  <p>GroopiePets</p>
  <footer>to pets lovers</footer>
</blockquote>
<div class="gallery row">
</div>
<div class='close-form' style="display: none;">close the form</div>
<%= render "shared/devise_log_out" %>
<%= render 'shared/modal_form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>GroopiePets</title>
  <meta content="Enseña tus mascotas a otros usuarios." name="description">
  <meta content="Raúl Cabrera Medina" name="author">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %> <%= true if current_user %>">
  <div class="container-fluid">
    <%= yield %>
  </div>
  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/layouts/clean.html.erb
<!DOCTYPE html>
<html>
<body>
  <div class="container-fluid">
    <%= yield %>
  </div>
  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/pets/form.html.erb
<%= form_for @pet, url: pets_create_path(@pet), method: :post, html: {class: ""} do |f| %>
  <div class="form-group">
    
    <%= f.hidden_field :id, value: @pet.id %>
    
    <%= f.label :name, :class => 'sr-only' %><br />
    <div class="input-group">
      <div class="input-group-addon">Pet's name</div>
      <%= f.text_field :name, :class => 'form-control', autofocus: true %>
    </div>
    
    <%= f.label :animal, :class => 'sr-only' %><br />
    <div class="input-group">
      <div class="input-group-addon">Type</div>
      <% options = Pet.animal_species.map { |animal| [animal.capitalize, animal]} %>
      <%= f.select :animal, options_for_select(options, @pet.animal), {:prompt => "select a category : "}, {:required => true, :class => 'form-control'} %>
    </div>

    <%= f.label :birth, :class => 'sr-only' %><br />
    <div class="input-group">
      <div class="input-group-addon">Age's pet</div>
      <%= f.date_select :birth, :class => 'form-control', order: [:day, :month, :year], :max_years_allowed => 20, :end_year => Date.today.year %>
    </div>
    
    <%= f.label :image, :class => 'sr-only' %><br />
    <div class="center-block">
      <div id="btn-image" class="btn btn-primary btn-lg btn-block center-block">Upload image</div>
      <%= f.file_field :image, style: "display: none;", id: "input-img-file" %>
      <%= image_tag(@pet.image.url(:thumb), class: "img-responsive img-thumbnail center-block", alt: "no image load", id: "form-img-sample" ) %>
      <div id="image_input_text" class="form-control"></div>
    </div>
    
  </div>

  <% if @pet.id == nil %>
    <%= f.submit "Save", name: "commit", class: "btn btn-primary btn-lg btn-block button-form" %>
  <% elsif current_user.id == @pet.user_id %>
    <%= f.submit "Update", name: "commit", class: "btn btn-success btn-lg btn-block update-form" %>
    <%= f.submit "Delete", name: "commit", class: "btn btn-danger btn-lg btn-block delete-form" %>
  <% end %>

<% end %>

app/views/shared/_devise_alerts.html.erb
<% if notice %>
  <p class="notice alert alert-info text-center"><%= notice %></p>
<% elsif alert %>
  <p class="alert alert-danger text-center"><%= alert %></p>
<% else %>
  <p class="notice alert alert-info text-center"></p>
<% end %>

app/views/shared/_devise_log_out.html.erb
<% if current_user %>
  <div class="devise_links">
    <%= link_to "Log out", destroy_user_session_path(), :method => 'delete', id: "log-out" %>
  </div>
<% end %>

app/views/shared/_modal_form.html.erb
<div id="myForm" class="row" data-name=<%="#{current_user.name}"%> style="display: none;">
</div>